### ISSUE TITLE
Changes not applied on window resize even after installing beta.23 version

### ISSUE THREAD

**Issue by ArchanaVijayaragavan** [angular/flex-layout#1017]
# Bug Report

#### What is the expected behavior?
When I resize the window, I expect that the fxLayout.lt-md, ngStyle.gt-xs, fxFlexOrder, etc directives are applied.

#### What is the current behavior?
Page resize does not trigger changes in layout based on using the responsive directives.

Everything was working in beta 19, responsive layouts broken by 20, and as of 23, the layout works on page load but when resizing the page, the directives aren't applied.

This is similar to the issue #947, as per the changelog  of beta.23 version it is mentioned that the issue got resolved, but i can still see the issue persisting.

#### What are the steps to reproduce?
In this stackblitz: https://stackblitz.com/edit/angular-flex-layout-seed-xoetvd?file=app/test.component.ts try resizing the window. The initial resize works but if you shrink it back, the style doesn't return to how it started out.

**Comment by CaerusKaru** [comment]
Duplicate of #1010

**Comment by CaerusKaru** [comment]
Actually upon further investigation, this looks like a separate issue. I'm going to reopen and then investigate further.

**Comment by olaf89** [comment]
I have the same issue

For example when i use ngClass.gt-sm="invisible" once its applied and window is resized the class stays on screen size xs.

**Comment by SegesDesign** [comment]
I have the same issue. However, it seems to work for native elements. 
E.g. this does not work after resize:
`<app-component [ngClass.gt-sm]="'big'"></app-component >`
This does work after resize:
`<div [ngClass.gt-sm]="'big'"></div>`
Like others said, the initial class is set correctly, but once the 'big' class gets added after resizing it is not removed anymore.

**Comment by CaerusKaru** [comment]
The demo uses 7.0.0-beta.22. After upgrading it to 7.0.0-beta.23 the demo works fine. Can you provide a demo that shows this not working with 7.0.0-beta.23?

If this isn't working for you locally, try forcing a fresh install of latest.

**Comment by SegesDesign** [comment]
Yes, I'm running beta 23. Ill look into if i can provide a demo.

**Comment by SegesDesign** [comment]
Here is a basic example. If you resize the windows it add the class correctly, but it is never removed again.
https://stackblitz.com/edit/angular-ybtwpv

**Comment by CaerusKaru** [comment]
@SegesDesign That one was fixed by #995

**Comment by ArchanaVijayaragavan** [comment]
Hi @CaerusKaru ,
I tried installing the latest version beta.24, but i could still see the issue persisting.

Issue:
Page resize does not trigger changes in layout based on using the responsive directives.
Responsive layouts were working fine till beta.19 but it is broken in all the recent releases.

When can we expect the fix for this?

**Comment by CaerusKaru** [comment]
@ArchanaVijayaragavan if the provided fix did not fix the issue for you, please provide another demo in a new issue. The one you provided no longer demonstrates the issue with the latest release.
