### ISSUE TITLE
useColumnBasisZero:false not applied in production builds

### ISSUE THREAD

**Issue by gerardcarbo** [angular/flex-layout#1035]
# Bug Report

#### What is the expected behavior?

When FlexLayoutModule.withConfig({useColumnBasisZero: false}) is specified, fxFlex default output shoud be flex:1 1 auto

#### What is the current behavior?

In production builds it still produces flex: 1 1 1e-9px

#### What are the steps to reproduce?

Install:

https://github.com/gerardcarbo/flex-layout-test

and run: 

`npm build && npm start`

The span where fxFlex is applied has the style: 

`style="flex: 1 1 1e-09px; box-sizing: border-box"`

If you run:

 `ng serve ` 

the same span has the style:

`style="flex: 1 1 auto; box-sizing: border-box;"`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

 ```
 "dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/cdk": "^7.3.4",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/flex-layout": "^7.0.0-beta.23",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "core-js": "^2.5.4",
    "http-server": "^0.11.1",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular/cli": "~7.3.0",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2"
  }
```

#### Is there anything else we should know?

To generate the test I just ran ng new, configured --prod flag and added the fxFlex to the span after installing @angular/flex-layout module

**Comment by CaerusKaru** [comment]
You have this backwards. `useColumnBasisZero` means exactly that: whether the `basis` (the last argument in the `flex` property declaration) is zero by default. When this value is set to true, you'll get `flex: 1 1 0`. When you set it to false, you get `flex: 1 1 1e-9px`. By default, the value is true.

**Comment by CaerusKaru** [comment]
In both cases, using latest version of Flex Layout, I'm getting `flex: 1 1 auto`, which is the intended behavior. I'm closing this issue, but if another demo is provided we can reopen.

**Comment by gerardcarbo** [comment]
I've published the output of the production build (--prod) of the provided sample using ngh in:

https://gerardcarbo.github.io/flex-layout-test/

As you can see, using the latest @angular/flex-layou 7.0.0-beta.23, it sets flex: 1 1 1e-09px to the span:

![image](https://user-images.githubusercontent.com/9449644/54489253-a9af7800-48aa-11e9-9c73-865897d296d5.png)

**Comment by gerardcarbo** [comment]
I can not provide you a stackblitz demo because the problem is in the production build (ng build **--prod**) but I have rechecked in a clean ubuntu instalation and you can reproduce the bug with:

```
sudo npm install -g npx 
git clone https://github.com/gerardcarbo/flex-layout-test.git
cd flex-layout-test/
npm run build
npm run serve_build
```
![image](https://user-images.githubusercontent.com/9449644/54528805-4abb3300-497e-11e9-8884-e95f1f33ab35.png)

**Comment by Yanal-Yves** [comment]
Hello,

Thank you for this library I like. I am running into the same issue.
I am still seeing flex: 1 1 1e-09px; in production build only with 7.0.0-beta.24.
What's the status of this issue please and thus what are the new milestones ?

**Comment by Yanal-Yves** [comment]
I don't if that helps, on my app:
With 7.0.0-beta.21, I am experiencing the issue.
7.0.0-beta.20, I don't have the issue but my app layout is a mess.
With 7.0.0-beta.19 I don't have the issue.

**Comment by Ghostbird** [comment]
Issue still exists in 7.0.0-beta.24

**Comment by Cowlephant** [comment]
Experiencing this issue as well exactly as described, not been able to successfully reproduce it outside of my production codebase.

**Comment by christurnbull** [comment]
The problem only occurs when building using AOT
(tested with: ng-core v7.2.15, ng-cli v7.3.9 , flex-layout 7.0.0-beta.24)

[This workaround fixed it with AOT for me](https://github.com/angular/flex-layout/issues/778#issuecomment-398641517)

**Comment by CaerusKaru** [comment]
If someone updates this to v9 Angular and the nightly Flex Layout builds, I'll investigate before the (planned) Tuesday release.

**Comment by CaerusKaru** [comment]
No response for a year, resolving as stale. If this is still an issue with v13, we can investigate.
