### ISSUE TITLE
fxLayout="row" fxLayoutWrap fxLayoutGap="10px" gives an offset starting at the 2nd line

### ISSUE THREAD

**Issue by maxime1992** [angular/flex-layout#108]
```
<div fxLayout="row" fxLayoutWrap fxLayoutGap="10px">
  <div class="card" fxFlex="25%" *ngFor="let i of [1, 2, 3, 4, 5, 6, 7, 8, 9]">
    Test
  </div>
</div>
```
![image](https://cloud.githubusercontent.com/assets/4950209/21839952/f3822d08-d7da-11e6-9803-110bb9352303.png)

https://plnkr.co/edit/f44sdpW159qKSGvWkWm5?p=preview

(probably) related to #106 except that here the layout is set to `row`

**Comment by d3viant0ne** [comment]
@maxime1992 - Different issue than #106. In this case the gap is being assigned to each card but the first which is where the weird offset is coming from.

**Comment by d3viant0ne** [comment]
@ThomasBurleson - Given the way elements wrap, wouldn't it make more sense to use `margin-right` for `layout-gap`

**Comment by d3viant0ne** [comment]
Resolved with f35c58f

**Comment by maxime1992** [comment]
I tried to upgrade from 2.0.0-beta.1 to 2.0.0-beta.4 and the problem is still here on my end.

Take a look to the previous Plunkr : https://plnkr.co/edit/f44sdpW159qKSGvWkWm5?p=preview
I dig into lib/config.js, and I tried to access to
[https://unpkg.com/@angular/flex-layout/bundles/flex-layout.umd.js](https://unpkg.com/@angular/flex-layout/bundles/flex-layout.umd.js)
which redirects me to : 
[https://unpkg.com/@angular/flex-layout@2.0.0-beta.4/bundles/flex-layout.umd.js](https://unpkg.com/@angular/flex-layout@2.0.0-beta.4/bundles/flex-layout.umd.js)

so Plunkr is using the latest version and the gap issue is still here.

I think this issue should be re opened.

**Comment by prateek0103** [comment]
For a quick workaround, I added CSS rule `margin-left` equal to the `fxLayoutGap` value to the first element. Check out this [plnk](https://plnkr.co/edit/YmA8HMzzfGSvS9HsiSjr?p=preview)

This needs a fix and should be reopened.

**Comment by ThomasBurleson** [comment]
@d3viant0ne - f35c58f does not address issues manifesting when **fxLayoutWrap** is used.

> I suggest the following changes:
*  `margin-right` be used with `fxLayout="row" fxLayoutWrap` combinations
*  `margin-bottom` be used with `fxLayout="column" fxLayoutWrap` combinations

**Comment by kousik77** [comment]
how to set margin top and bottom

**Comment by spt131** [comment]
Any fix for this? Using 2.0 rc1 doesn't resolve.

**Comment by tabruzzomufg** [comment]
?? having the same issue? any fixes for this?
