### ISSUE TITLE
Property 'currentActivations' implicitly has type 'any'

### ISSUE THREAD

**Issue by arminas-saltenis** [angular/flex-layout#1302]
# Bug Report
#### What is the current behavior?
When building an application with flex-layout I get an error that says:

> ERROR in node_modules/@angular/flex-layout/core/typings/media-trigger/media-trigger.d.ts:66:17 - error TS7033: Property 'currentActivations' implicitly has type 'any', because its get accessor lacks a return type annotation.
> 
> private get currentActivations();

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Using:
`
"@angular/core": "9.0.0-rc.8"
"@angular/cdk": "^8.2.3"
"@angular/flex-layout": "9.0.0-beta.28"
"@angular/material": "^8.2.1"
`

**Comment by CaerusKaru** [comment]
This should be fixed in the v10 beta. Can you upgrade and check?

**Comment by arminas-saltenis** [comment]
> This should be fixed in the v10 beta. Can you upgrade and check?

This is still happening with the version `"@angular/flex-layout": "10.0.0-beta.32"`.
Updated the version, deleted node_modules and started npm install.

**Comment by CaerusKaru** [comment]
I really don't know what to tell you. This was fixed back in beta 30 (see [here](https://github.com/angular/flex-layout/commit/1faa45cb3702f2c1d9cf1b59f5f665811b74b0bd#diff-de0df1e07ea90adfa1e54f88b95bc4f1e8b44f9429d6e657d910be637fcc287f). Maybe check your package-lock.json?

In the meantime, I'm marking this as a duplicate of #1217 unless there's tangible evidence something else is going on.
