### ISSUE TITLE
StyleDirective throws renderer error '_ngEl.nativeElement.getAttribute is not a function'

### ISSUE THREAD

**Issue by aaronte** [angular/flex-layout#408]
Trying to run `@angular/flex-layout#2.0.0-beta.9` with universal and getting this error:

```bash
Unhandled Promise rejection: _ngEl.nativeElement.getAttribute is not a function ; Zone: <root> ; Task: Promise.then ; Value: { TypeError: _ngEl.nativeElement.getAttribute is not a function
    at new StyleDirective (/user_code/node_modules/@angular/flex-layout/bundles/flex-layout.umd.js:3087:61)
    at createClass (/user_code/node_modules/@angular/core/bundles/core.umd.js:10970:26)
    at createDirectiveInstance (/user_code/node_modules/@angular/core/bundles/core.umd.js:10788:37)
    at createViewNodes (/user_code/node_modules/@angular/core/bundles/core.umd.js:12229:49)
    at callViewAction (/user_code/node_modules/@angular/core/bundles/core.umd.js:12675:13)
    at execComponentViewsAction (/user_code/node_modules/@angular/core/bundles/core.umd.js:12584:13)
    at createViewNodes (/user_code/node_modules/@angular/core/bundles/core.umd.js:12256:5)
    at createRootView (/user_code/node_modules/@angular/core/bundles/core.umd.js:12124:5)
    at Object.createProdRootView [as createRootView] (/user_code/node_modules/@angular/core/bundles/core.umd.js:12809:12)
    at ComponentFactory_.create (/user_code/node_modules/@angular/core/bundles/core.umd.js:9896:46)
  __zone_symbol__currentTask: 
   ZoneTask {
     _zone: 
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [Object] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data: undefined,
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } } TypeError: _ngEl.nativeElement.getAttribute is not a function
    at new StyleDirective (/user_code/node_modules/@angular/flex-layout/bundles/flex-layout.umd.js:3087:61)
    at createClass (/user_code/node_modules/@angular/core/bundles/core.umd.js:10970:26)
    at createDirectiveInstance (/user_code/node_modules/@angular/core/bundles/core.umd.js:10788:37)
    at createViewNodes (/user_code/node_modules/@angular/core/bundles/core.umd.js:12229:49)
    at callViewAction (/user_code/node_modules/@angular/core/bundles/core.umd.js:12675:13)
    at execComponentViewsAction (/user_code/node_modules/@angular/core/bundles/core.umd.js:12584:13)
    at createViewNodes (/user_code/node_modules/@angular/core/bundles/core.umd.js:12256:5)
    at createRootView (/user_code/node_modules/@angular/core/bundles/core.umd.js:12124:5)
    at Object.createProdRootView [as createRootView] (/user_code/node_modules/@angular/core/bundles/core.umd.js:12809:12)
    at ComponentFactory_.create (/user_code/node_modules/@angular/core/bundles/core.umd.js:9896:46)
```

Not sure if I'm using some deprecated stuff. Help?

**Comment by aaronte** [comment]
Happens when `[ngStyle]` is used.

**Comment by ThomasBurleson** [comment]
This should be fixed with PR #398 and other changes in `master`.

**Comment by ThomasBurleson** [comment]
Fixed with SHA 816d85a66dd323fa1092d41f0f8567b7787c22c1

**Comment by cupidi** [comment]
I'm still getting this error even though I'm using the nightly ```@angular/flex-layout@2.0.0-beta.9-5f198a3```

**Comment by ThomasBurleson** [comment]
@cupidi - can you provide a plunkr or code for our team to use?

**Comment by naveedahmed1** [comment]
Same here, I am also using `@angular/flex-layout@2.0.0-beta.9-5f198a3` and having same issue.

**Comment by ThomasBurleson** [comment]
Fixed with SHA e461d17471f713deaf4663e0a0438822f8f0ad86

**Comment by calvinmuller** [comment]
This is not yet merged into any public release?

**Comment by ThomasBurleson** [comment]
Not yet: see https://github.com/angular/flex-layout/issues/344#issuecomment-335493236
