### ISSUE TITLE
2.0.0-beta.10 throws 'Can't resolve rxjs/operators'

### ISSUE THREAD

**Issue by mattiLeBlanc** [angular/flex-layout#483]
I am running Angular-CLI version:
@angular/cli: 1.4.6
node: 6.9.5
os: darwin x64
@angular/animations: 4.4.5
@angular/common: 4.4.5
@angular/compiler: 4.4.5
@angular/core: 4.4.5
@angular/flex-layout: 2.0.0-beta.9
@angular/forms: 4.4.5
@angular/http: 4.4.5
@angular/platform-browser: 4.4.5
@angular/platform-browser-dynamic: 4.4.5
@angular/router: 4.4.5
@angular/cli: 1.4.6
@angular/compiler-cli: 4.4.5
@angular/language-service: 4.4.5
typescript: 2.3.4

After installing flex-layout and adding the import, I got this error:
`@angular/flex-layout/esm5/flex-layout.es5.js Module not found: Error: Can't resolve 'rxjs/operators' in`

Downgrading to `2.0.0-beta.9` resolved the error.

**Comment by Manduro** [comment]
Updating Rxjs to 5.5.x should solve this!

**Comment by jotatoledo** [comment]
Check that your dependencies match the perDependencies of flex-layout

**Comment by leerenold** [comment]
@Manduro upgrading to 5.5.x does not resolve. flex-layout is requiring 'rxjs/operators' which is not present in lates rxjs too.

**Comment by mattiLeBlanc** [comment]
@jotatoledo Mate, keep your thumbs in check.
Looking at the release notes there is not way for a non 'project immersed person' to know I have to upgraded my RXJS to before installing the latest version of flex-layout.

I installed flex-layout a month ago and this was Beta.9 and it worked fine with the current version 4.4.4. I started a new project last week using NG CLI and added fley-layout yesterday which turned out to be version Beta.10. I am not going to upgrade everything before I add a new library because of possible adverse affects.

Even if the dependencies says 5.5 doesn't always mean it wouldn't work on another version. It should have been mentioned in the release notes.

Apparently upgrading RXJS tot 5.5 didn't even resolve the issue according to @leerenold

**Comment by jotatoledo** [comment]
could you please confirm if this has no effect for your issue? There are some changes made to the angular-cli becauae of the lettable operators in rxjs 5.5.x, check the release notes of the v1.4.9. maybe thats related

**Comment by ThomasBurleson** [comment]
Angular 5 has a dependency on RXJS 5.5. Unfortunately, Angular 4 does not. 
> Since `@angular/flex-layout` has peerDependency of 4.4... this issue has unexpectedly manifested.

**Comment by mattiLeBlanc** [comment]
I can confirm that updating RXJS tot 5.5.2 removed the issue.
I will try upgrading to latest CLI and Angular version (5?) and see how it runs.
Should we keep on upgrading every time? I guess in a production environment you want to freeze certain version because a NPM install on our CI servers might cause a build failure at times.
