### ISSUE TITLE
Flexlayout not compatible with material 5

### ISSUE THREAD

**Issue by elineopsommer** [angular/flex-layout#492]
#### Bug, feature request, or proposal:
Bug
When using flexLayout rows, the two mat-form-fields next to each other do not take the proper space, the two mat-form-fields together should be properly aligned with the third input (email)

#### What is the expected behavior?
![localhost_4200_monitors_add 1](https://user-images.githubusercontent.com/11610110/32492081-53b2f67e-c3b9-11e7-90ff-9159c896f037.png)

#### What is the current behavior?
![schermafbeelding 2017-11-07 om 11 48 33](https://user-images.githubusercontent.com/11610110/32491928-bcc46fcc-c3b8-11e7-889f-f29ebe6ca8ed.png)

#### What are the steps to reproduce?

Small piece of code is provided:

```
<form fxLayout="column" [formGroup]="registerForm">
   <div class="input-row" fxLayout="row" fxLayout.sm="column" fxLayout.xs="column" fxLayoutGap="20px">
    <mat-form-field fxFlex>
      <input matInput
             type="text"
             placeholder="FIRSTNAME" formControlName="firstName">
    </mat-form-field>

    <mat-form-field fxFlex>
      <input matInput
             type="text"
             placeholder="LASTNAME" formControlName="lastName">
    </mat-form-field>
  </div>

  <div class="input-row">
    <mat-form-field fxFill>
      <input matInput
             type="email"
             placeholder="EMAIL"
             email
             formControlName="email">
    </mat-form-field>
  </div>
</form>

```

#### What is the use-case or motivation for changing an existing behavior?
Existing behaviour broken

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular5, Material 5

**Comment by RainingNight** [comment]
Not compatible angular5.

**Comment by ThomasBurleson** [comment]
@RainingNight - The latest release of @angular/flex-layout **IS** compatible with Angular 5. Please delete your `node_modules` dir, `npm i`, and try again.

**Comment by ThomasBurleson** [comment]
@elineopsommer - Since @angular/material uses custom wrapper elements, you may experience layout issues. However, in this [StackBlitz Demo](https://stackblitz.com/edit/angular-mat-formfield-flex-layout?file=app/app.component.ts), it appears to be working:

![screen shot 2017-11-28 at 3 46 49 pm](https://user-images.githubusercontent.com/210413/33345892-7c982c3a-d453-11e7-8dd2-03d89b616c92.png)

> Note: the demo uses latest versions of Angular 5.x, Angular Material 5.x, and Flex-Layout 2 Beta.11

**Comment by ThomasBurleson** [comment]
Closing as not-an-issue.

**Comment by playground** [comment]
@ThomasBurleson StackBlitz Demo is not working.

![image](https://user-images.githubusercontent.com/243495/34644974-1f7732f4-f310-11e7-9309-6878f01c51e0.png)

**Comment by ThomasBurleson** [comment]
@playground - The BrowserAnimationsModule was not loaded. [Fixed here](https://stackblitz.com/edit/angular-mat-formfield-flex-layout?file=app%2Fapp.module.ts)

**Comment by playground** [comment]
hmm... @ThomasBurleson still seeing the same behavior with BrowserAnimationsModule loaded.

![image](https://user-images.githubusercontent.com/243495/34652185-e3d01100-f3a8-11e7-85d9-fe0b885b72da.png)

**Comment by ThomasBurleson** [comment]
@playground - You realize you never explained what is not working properly. Please provide details.

**Comment by playground** [comment]
Sorry thought the screenshot explained the first and last name fields should be on the same line.

**Comment by ThomasBurleson** [comment]
@playground - the Demo uses `fxLayout.lt-md="column"` mode. So for `md` or higher, the First and LastName fields are on the same line.

**Comment by scorbin** [comment]
Still not working if you add more mat-form-field they will overflow the container.  Maybe you have to wrap each mat-form-field in a div
